# when thersholds are provided it means random 1-100 must exceed the value

# ENEMIES
# base params
ATK_LV_1 = 10
ATK_LV_2 = 15
ATK_LV_3 = 20
ATK_LV_4 = 30

DEF_LV_1 = 10
DEF_LV_2 = 15
DEF_LV_3 = 25
DEF_LV_4 = 35

MAX_ENEMY_HP_FACTOR = 10

MIN_ENEMY_ATK_SHIFT = -5
MAX_ENEMY_ATK_SHIFT = 5

MIN_ENEMY_DEF_SHIFT = -5
MAX_ENEMY_DEF_SHIFT = 5

BOSS_HP_FACTOR = 1.5
BOSS_ATK_FACTOR = 1.25
BOSS_DEF_FACTOR = 1.25

# specials
HYENA_SPECIAL_HP_THRESHOLD = 25
HYENA_SPECIAL_ATK_FACTOR = 2

WOLF_BLEEDING_CHANCE_THRESHOLD = 50
BLEEDING_LOSS_VALUE = 5

WEREWOLF_SPECIAL_HP_THRESHOLD = 25
WEREWOLF_HP_RECOVERY = 10

# reward
THREE_LOOT_ITEMS_CHANCE_THRESHOLD = 90
TWO_LOOT_ITEMS_CHANCE_THRESHOLD = 70

MIN_GOLD_REWARD = 3
MAX_GOLD_REWARD = 10

EQUIPMENT_CHANCE_THRESHOLD = 70
LOOT_CHANCE_THRESHOLD = 30

# spawn thresholds
STAGE_2_LV_1_SPAWN_THRESHOLD = 90

STAGE_3_LV_1_SPAWN_THRESHOLD = 90
STAGE_3_LV_2_SPAWN_THRESHOLD = 80

STAGE_4_LV_1_SPAWN_THRESHOLD = 90
STAGE_4_LV_2_SPAWN_THRESHOLD = 80
STAGE_4_LV_3_SPAWN_THRESHOLD = 70

# other
ALEG_DRINKS_TO_BAD_ENDING = 4


# ITEMS
BEER_DRUNK = 10

FOOD_HP = 20
FOOD_DRUNK_LOSS = 2

MIN_CHEST_GOLD_REWARD = 1
MAX_CHEST_GOLD_REWARD = 5


# LOCATIONS
ENEMIES_IN_LOCATION_THRESHOLD = 50

TURNS_WITHOUT_TAVERN = 10
TAVERN_SPAWN_THRESHOLD = 90

NPC_SPAWN_THRESHOLD = 90

CHEST_SPAWN_THRESHOLD = 95
CHEST_LUCK_FACTOR = 2


# PLAYER
PLAYER_HP = 100
PLAYER_ATK = 10
PLAYER_DEF = 10
PLAYER_ENDURANCE = 1
PLAYER_STRENGTH = 1
PLAYER_AGILITY = 1
PLAYER_LUCK = 1
INITIAL_GOLD = 10

MAX_HP_ENDURANCE_FACTOR = 20

PLAYER_ATK_FACTOR = 5
PLAYER_DEF_FACTOR = 5


# SCENE
DRUNK_FOR_MOVING = 1

MIN_LOCATION_SIZE = 2
MAX_LOCATION_SIZE = 5

# battle
DEFAULT_HIT_CHANCE = 20
HIT_LUCK_FACTOR = 1.5
HIT_DRUNK_FACTOR = 2
CRIT_ATK_FACTOR = 2

VULNERABILITY_FACTOR = 2
RESIST_FACTOR = 0.5

RUN_AWAY_THRESHOLD = 40
RUN_AWAY_LUCK_FACTOR = 10
RUN_AWAY_DRUNK_FACTOR = 0.5

RUN_AWAY_DRUNK_LOSS = 1
FINISH_BATTLE_DRUNK_LOSS = 3

# npc
NPC_QUEST_CHANCE_THRESHOLD = 20
NPC_DRINK_CHANCE_THRESHOLD = 60

# quests
MIN_QUEST_ENEMIES_AMOUNT = 2
MAX_QUEST_ENEMIES_AMOUNT = 5
GOLD_REWARD_FOR_QUEST_PER_ENEMY = 5
MIN_QUEST_ADDITIONAL_REWARD = 2
MAX_QUEST_ADDITIONAL_REWARD = 10


# TAVERN
BEER_PRICE = 5
FOOD_PRICE = 5

ALEG_SPAWN_CHANCE_THRESHOLD = 66
